services:
  - type: web
    name: noww-club-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Noww_club.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
